### PR TITLE
Add pull request description template

### PR DESCRIPTION
**Pull request by agirivera**
## Summary
- Adds pull request description template

/cc @juwai/platform-all @imlazyone @tjoelsson Please review. Thanks.

### CODE REVIEW

**Comment by tjoelsson** [comment]
👍

**Comment by stuartwan** [comment]
💯

**Comment by HouCoder** [comment]
Don't forget update related issue

**Comment by agirivera** [comment]
Tagging https://github.com/juwai/in-house/issues/74 for visuals.

**Comment by agirivera** [comment]
Thanks guys.

**Pull request merged**
